### ISSUE TITLE
Crashes when clicking the 'X' button on Symptom and History Form

### ISSUE THREAD

**Issue by ellyasafaa** [sid-indonesia/rdt-standard#7]
Replicated on Samsung A21s Android 10 and Oppo A5s Android 8

https://drive.google.com/file/d/13cw2YAfA0yUNsy_tr4lxg5UQu4E2LpVa/view?usp=sharing

**Comment by ellyasafaa** [comment]
```2021-06-04 16:05:06.580 22623-22623/io.ona.diagnostics.rdt.configurable.id E/Zygote: isWhitelistProcess - Process is Whitelisted
2021-06-04 16:05:06.582 22623-22623/io.ona.diagnostics.rdt.configurable.id E/Zygote: accessInfo : 1
2021-06-04 16:05:06.627 22623-22623/io.ona.diagnostics.rdt.configurable.id E/configurable.i: Unknown bits set in runtime_flags: 0x8000
2021-06-04 16:06:24.285 22623-22623/io.ona.diagnostics.rdt.configurable.id E/Context: java.io.FileNotFoundException: bindtypes.json
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:875)
        at org.smartregister.Context.ReadFromfile(Context.java:1082)
        at org.smartregister.Context.assignbindtypes(Context.java:1003)
        at org.smartregister.Context.sharedRepositories(Context.java:545)
        at org.smartregister.Context.sharedRepositoriesArray(Context.java:567)
        at io.ona.rdt.repository.RDTRepository.<init>(RDTRepository.java:30)
        at io.ona.rdt.application.RDTApplication.getRepository(RDTApplication.java:98)
        at org.smartregister.repository.DrishtiRepository.masterRepository(DrishtiRepository.java:16)
        at org.smartregister.repository.SettingsRepository.querySetting(SettingsRepository.java:74)
        at org.smartregister.repository.AllSettings.fetchANMLocation(AllSettings.java:61)
        at org.smartregister.view.controller.ANMLocationController$1.fetch(ANMLocationController.java:25)
        at org.smartregister.view.controller.ANMLocationController$1.fetch(ANMLocationController.java:22)
        at org.smartregister.util.Cache.get(Cache.java:66)
        at org.smartregister.view.controller.ANMLocationController.get(ANMLocationController.java:22)
        at org.smartregister.location.helper.LocationHelper.map(LocationHelper.java:681)
        at org.smartregister.location.helper.LocationHelper.generateDefaultLocationHierarchy(LocationHelper.java:233)
        at org.smartregister.location.helper.LocationHelper.generateDefaultLocationHierarchy(LocationHelper.java:222)
        at org.smartregister.location.helper.LocationHelper.getDefaultLocation(LocationHelper.java:128)
        at io.ona.rdt.util.CovidRDTJsonFormUtils.getDefaultLocations(CovidRDTJsonFormUtils.java:201)
        at io.ona.rdt.util.CovidRDTJsonFormUtils.getLocations(CovidRDTJsonFormUtils.java:193)
        at io.ona.rdt.util.CovidRDTJsonFormUtils.prePopulateRDTPatientFields(CovidRDTJsonFormUtils.java:156)
        at io.ona.rdt.util.CovidRDTJsonFormUtils.prePopulateFormFields(CovidRDTJsonFormUtils.java:86)
        at io.ona.rdt.util.RDTJsonFormUtils.launchForm(RDTJsonFormUtils.java:264)
        at io.ona.rdt.util.FormLauncher.launchForm(FormLauncher.java:39)
        at io.ona.rdt.util.FormLauncherAndSaver.launchForm(FormLauncherAndSaver.java:24)
        at io.ona.rdt.presenter.CovidPatientProfileFragmentPresenter.launchForm(CovidPatientProfileFragmentPresenter.java:29)
        at io.ona.rdt.fragment.CovidPatientProfileFragment.onClick(CovidPatientProfileFragment.java:60)
        at android.view.View.performClick(View.java:7862)
        at android.widget.TextView.performClick(TextView.java:15004)
        at android.view.View.performClickInternal(View.java:7831)
        at android.view.View.access$3600(View.java:879)
        at android.view.View$PerformClick.run(View.java:29359)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2021-06-04 16:06:25.124 22623-22623/io.ona.diagnostics.rdt.configurable.id E/DecorView: mWindow.mActivityCurrentConfig is null
2021-06-04 16:06:25.938 22623-22623/io.ona.diagnostics.rdt.configurable.id E/DecorView: mWindow.mActivityCurrentConfig is null
2021-06-04 16:06:26.031 22623-22623/io.ona.diagnostics.rdt.configurable.id E/ViewRootImpl: sendUserActionEvent() mView returned.
2021-06-04 16:06:52.043 22623-22623/io.ona.diagnostics.rdt.configurable.id E/DecorView: mWindow.mActivityCurrentConfig is null
2021-06-04 16:06:52.769 22623-22623/io.ona.diagnostics.rdt.configurable.id E/ViewRootImpl: sendUserActionEvent() mView returned.
2021-06-04 16:07:02.539 22623-22623/io.ona.diagnostics.rdt.configurable.id E/DRISHTI: Rhino initialization failed. We are screwed. EOW!!!. Evil: org.mozilla.javascript.EcmaError: ReferenceError: "require" is not defined. (code#1)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.smartregister.commonregistry.CommonRepository.isFts()' on a null object reference
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at org.smartregister.cursoradapter.RecyclerViewFragment.isValidFilterForFts(RecyclerViewFragment.java:516)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at org.smartregister.cursoradapter.RecyclerViewFragment.countExecute(RecyclerViewFragment.java:480)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at io.ona.rdt.presenter.PatientRegisterFragmentPresenter.initializeQueries(PatientRegisterFragmentPresenter.java:48)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at org.smartregister.view.fragment.BaseRegisterFragment.renderView(BaseRegisterFragment.java:262)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at org.smartregister.view.fragment.BaseRegisterFragment.onResumption(BaseRegisterFragment.java:255)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at io.ona.rdt.fragment.PatientRegisterFragment.onResume(PatientRegisterFragment.java:45)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.fragment.app.Fragment.performResume(Fragment.java:2748)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:373)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1211)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1830)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:246)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.View.measure(View.java:26411)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.View.measure(View.java:26411)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.View.measure(View.java:26411)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
2021-06-04 16:07:02.963 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.View.measure(View.java:26411)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.View.measure(View.java:26411)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.View.measure(View.java:26411)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1050)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.View.measure(View.java:26411)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3638)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2373)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2665)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.Choreographer.doCallbacks(Choreographer.java:797)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.Choreographer.doFrame(Choreographer.java:732)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.os.Handler.handleCallback(Handler.java:883)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.os.Handler.dispatchMessage(Handler.java:100)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.os.Looper.loop(Looper.java:237)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at android.app.ActivityThread.main(ActivityThread.java:8167)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at java.lang.reflect.Method.invoke(Native Method)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
2021-06-04 16:07:02.964 22623-22623/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2021-06-04 16:07:02.972 22623-478/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.smartregister.commonregistry.CommonRepository.isFts()' on a null object reference
        at org.smartregister.cursoradapter.RecyclerViewFragment.isValidFilterForFts(RecyclerViewFragment.java:516)
        at org.smartregister.cursoradapter.RecyclerViewFragment.countExecute(RecyclerViewFragment.java:480)
        at org.smartregister.cursoradapter.RecyclerViewFragment$2.loadInBackground(RecyclerViewFragment.java:537)
        at org.smartregister.cursoradapter.RecyclerViewFragment$2.loadInBackground(RecyclerViewFragment.java:532)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2021-06-04 16:07:02.973 22623-478/io.ona.diagnostics.rdt.configurable.id E/RecyclerViewFragment: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.smartregister.commonregistry.CommonRepository.isFts()' on a null object reference
        at org.smartregister.cursoradapter.RecyclerViewFragment.isValidFilterForFts(RecyclerViewFragment.java:516)
        at org.smartregister.cursoradapter.RecyclerViewFragment.filterandSortQuery(RecyclerViewFragment.java:427)
        at org.smartregister.cursoradapter.RecyclerViewFragment.access$200(RecyclerViewFragment.java:54)
        at org.smartregister.cursoradapter.RecyclerViewFragment$2.loadInBackground(RecyclerViewFragment.java:545)
        at org.smartregister.cursoradapter.RecyclerViewFragment$2.loadInBackground(RecyclerViewFragment.java:532)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2021-06-04 16:07:02.976 22623-478/io.ona.diagnostics.rdt.configurable.id E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
    Process: io.ona.diagnostics.rdt.configurable.id, PID: 22623
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor org.smartregister.commonregistry.CommonRepository.rawCustomQueryForAdapter(java.lang.String)' on a null object reference
        at org.smartregister.cursoradapter.RecyclerViewFragment$2.loadInBackground(RecyclerViewFragment.java:547)
        at org.smartregister.cursoradapter.RecyclerViewFragment$2.loadInBackground(RecyclerViewFragment.java:532)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```
